server:
  port: 8081
spring:
  application:
    name: study-nacos
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: true
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        enabled: true
